//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureSound.appCurr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pureSoundEntities : DbContext
    {
        public static pureSoundEntities _context;
        public pureSoundEntities()
            : base("name=pureSoundEntities")
        {
        }
    
        public static pureSoundEntities GetContext()
        {
            if (_context == null)
                _context = new pureSoundEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usersTable> usersTable { get; set; }
    }
}
