//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureSound.appCurr
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlistTracksTable
    {
        public int idPlTracks { get; set; }
        public int idPlaylist { get; set; }
        public string idTracks { get; set; }
    
        public virtual playlistsTable playlistsTable { get; set; }
    }
}
