//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureSound.appCurr
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlistsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public playlistsTable()
        {
            this.playlistTracksTable = new HashSet<playlistTracksTable>();
        }
    
        public int idPlaylist { get; set; }
        public int idUser { get; set; }
        public string namePlaylist { get; set; }
    
        public virtual usersTable usersTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlistTracksTable> playlistTracksTable { get; set; }
    }
}
