//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureSound.appCurr
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableFavourite
    {
        public int favTracks { get; set; }
        public int idUser { get; set; }
        public string idTrack { get; set; }
    
        public virtual usersTable usersTable { get; set; }
    }
}
