//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureSound.appCurr
{
    using Microsoft.Win32;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Diagnostics;
    using static NuGet.Client.ManagedCodeConventions;

    public partial class usersTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usersTable()
        {
            this.playlistsTable = new HashSet<playlistsTable>();
            this.tableFavourite = new HashSet<tableFavourite>();
        }

      
        public int idUser { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userLogin { get; set; }
        public string userPassword { get; set; }
        public string imageUser { get; set; }
        public string CurrentPhoto
        {
            get
            {
                if (string.IsNullOrEmpty(imageUser) || string.IsNullOrWhiteSpace(imageUser))
                {
                    return "/pages/player/profile.png";
                }
                else
                {
                    if (System.IO.File.Exists(imageUser))
                    {
                        return "" + imageUser;
                    }
                    else
                    {
                        return "/pages/player/profile.png";
                    }
                }
            }   
        }
        
       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlistsTable> playlistsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tableFavourite> tableFavourite { get; set; }
    }
}
